import crypto from "crypto";

import dotenv from "dotenv";
dotenv.config();

import { QdrantClient } from "@qdrant/js-client-rest";

const qdrant = new QdrantClient({
  url: process.env.QDRANT_URL,
  apiKey: process.env.QDRANT_API_KEY,
  checkCompatibility: false,
});

export default qdrant;

// Test Qdrant connection
export const testQdrantConnection = async () => {
  try {
    const response = await qdrant.getCollections();

    console.log("Qdrant connected successfully:", response.collections);
  } catch (error) {
    console.error("Qdrant connection failed:", error.message);
  }
};

// Create RepoGPT collection
export const createRepoGPTCollection = async () => {
  try {
    const collections = await qdrant.getCollections();

    const exists = collections.collections.some(
      (collection) => collection.name === "repogpt",
    );

    if (exists) {
      console.log("RepoGPT collection already exists");
      return;
    }

    await qdrant.createCollection("repogpt", {
      vectors: {
        size: 384,
        distance: "Cosine",
      },
    });

    console.log("RepoGPT collection created successfully");
  } catch (error) {
    console.error("Collection creation failed:", error.message);
  }
};

// Store embedded code chunks inside the Qdrant collection
export const storeEmbeddings = async (embeddedChunks, repositoryId) => {
  try {
    // Convert every embedded chunk into a Qdrant point
    const points = embeddedChunks.map((chunk, index) => ({
      // Qdrant requires a unique ID for every point
      id: crypto.randomUUID(),

      // The 384-dimensional vector generated by our AI service
      vector: chunk.embedding,

      // Metadata stored with the vector
      // This will help us find the original code later
      payload: {
        repositoryId: repositoryId.toString(),
        path: chunk.path,
        content: chunk.content,
      },
    }));

    // Insert/update all points in the "repogpt" collection
    await qdrant.upsert("repogpt", {
      wait: true,
      points,
    });

    console.log(`Stored ${points.length} embeddings in Qdrant`);
  } catch (error) {
    console.error("Failed to store embeddings:", error.message);

    // Send the error back to the controller
    // so the repository connection can report the failure
    throw error;
  }
};
